export const lines = {
  a: [
    "I can see us lost in the memory",
    "I can see us twisted in bedsheets",
    "Cause, darling, I'm a nightmare dressed like a daydream",
    "But they forgot to come and get me",
    "All my mornings are Mondays stuck in an endless February",
    "Romeo, save me, they're tryna tell me how to feel",
    "You found me, you found me, you found me",
    "He's long gone when he's next to me",
    "Now I heard you moved on from whispers on the street",
    "A new notch in your belt is all I'll ever be",
    "Nice to meet you, where you been?",
    "And I know you heard about me",
    "You're the King, baby, I'm your Queen",
    "But you were everything to me",
    "This love is difficult, but it's real",
    "I hit my peak at seven feet",
    "I know heaven's a thing, I go there when you touch me",
    "Out of all the bricks they threw at me",
    "The best people in life are free",
    "But every night with us is like a dream",
    "You almost ran the red 'cause you were lookin' over at me",
    "And your mother's telling stories 'bout you on the tee-ball team",
    "My boredom's bone deep",
    "They don't know how you've haunted me",
    "I wanna stay right here in this passenger seat",
    "Get me with those green eyes, baby",
    "And I could wait patiently",
    "In the good in the world, you once believed in me",
  ],
  b: [
    "But do you remember?",
    "Remember when I pulled up and said, 'Get in the car'",
    "It'll leave you breathless or with a nasty scar",
    "We'll take this way too far",
    "Run into you sometimes, ask about the weather",
    "I close my eyes and the flashback starts",
    "I'm drunk in the back of the car",
    "I cried like a baby coming home from the bar",
    "I take this magnetic force of a man to be my lover",
    "I have this thing where I get older but just never wiser",
    "I'll stare directly at the sun but never in the mirror",
    'All the pieces of me shattered as the crowd was chanting "More"',
    "I'm sure I can pass this test (one, two, three, four)",
    "Salt air, and the rust on your door",
    "Got a long list of ex-lovers",
    "Cross your heart, won't tell no other",
    "And smooth-talkin' hucksters out glad-handin' each other",
    "To a house, not a home, all alone 'cause nobody's there",
    "My friends found friends who care",
    "We show off our different scarlet letters",
    "Then switch sides like a record changer",
    "And I know it's long gone and that magic's not here no more",
    "Down the stairs, I was there",
    "I'm a crumpled up piece of paper lying here",
    "And, somehow, I know that you and I would've found each other",
    "And you know I wanna ask you to dance right there",
    "I run my fingers through your hair",
    "Is that your key in the door?",
  ],
  c: [
    "It's a cruel summer with you",
    "And I'm highly suspicious that everyone who sees you wants you",
    "My heart's been borrowed and yours has been blue",
    "All of the people I've ghosted stand there in the room",
    "Cuz we were both young when I first saw you",
    "Remember how I said I'd die for you?",
    "Daring you to leave me just so I can try and scare you",
    "You don't have to answer, just 'cause they asked you",
    "We cry tears of mascara in the bathroom",
    "Honey, life is just a classroom",
    "I walked through the door with you",
    "And I know it's long gone and there was nothing else I could do",
    "And I forget about you long enough to forget why I needed to",
    "Catastrophic blues",
    "Movin' on was always easy for me to do",
  ],
};
