export const lights = [
  'lights',
  'paints',
  'children',
  'moon',
  'fire',
  'eyes',
  'fuckwads',
  'snorsauges',
  'crabs',
  'clairvoyants',
  'carriages',
  'fences',
  'chant',
  'luces',
  'clock',
  'routers',
  'screens',
  'lovers',
  'spirales',
  'crash',
];
export const went = [
  'went',
  'blinked',
  'snuffed',
  'dimmed',
  'blew',
  'barged',
  'took',
  'sat',
  'scattered',
  'dreamed',
  'remained',
  'floated',
  'se',
  'wound',
  'shut',
  'switched',
  'wept',
  'se sont',
];
export const wordOut = [
  'out',
  'dark',
  'quiet',
  'off',
  'away',
  'in',
  'over',
  'down',
  'birdseed',
  'below',
  'uncut',
  'feuron',
  'down',
  'on',
  'onward',
  'accélérées',
];
export const before = [
  'before',
  'while',
  'underneath',
  'after',
  'eventually',
  'until',
  'despite',
  'thus',
  'in between',
  'yet',
  'tal vez',
  'under',
  'benumbed',
  'au même moment que',
];
export const darkness = [
  'darkness',
  'weight',
  'songs',
  'happiness',
  'night',
  'Appalachian Mountains',
  'apocalypse',
  'nines',
  'claws',
  'snow',
  'headlights',
  'pipes',
  'vapour',
  'oscuridad',
  'topsoil',
  'solitude',
  'splendor',
  'radiance',
  'time',
  'accident',
];
export const turnedOn = [
  'turned on',
  'changed',
  'hushed',
  'went away from',
  'switched on',
  'followed',
  'bored',
  'clattered quietly toward',
  'sidled from',
  'swept over',
  'ran through',
  'forbade',
  'contaminated',
  'distorted',
  'trickled out of',
  'left',
  'slowed',
  'excited',
];
export const uncheckedLove = [
  'unchecked love',
  'collections',
  'remembrance',
  'inexcusable thoughts',
  'commitment issues',
  'misplaced faith',
  'ambivalence',
  '(water)line',
  'queasy unease',
  'accretion',
  'bellies full',
  'infernal snippings',
  'voiceless cousin',
  'onstruyendo hambre',
  'derision',
  'mentorship',
  'rampant romance',
  'endless listlessness',
  'passion assumée',
  'wildchilding voyage',
];
export const dandelions = [
  'dandelions',
  'pillows',
  'the small things',
  'wood',
  'ashes',
  'out-of-print paperbacks',
  'assholes',
  'stomach',
  'chickadees',
  'minnows',
  'ivy',
  'chance',
  'arroz con pollo',
  'industry',
  'sparrows',
  'blueberry bushes',
  'every hour',
  'caresses',
  'discovery',
];
export const uncheckedLoveTwo = [
  'unchecked love',
  'union dues',
  'dreams',
  'depths',
  'fear',
  'mild confusion',
  'laughing our fucking asses off',
  'queasy unease',
  'ecology',
  'floating desires',
  'hard-pressed terror',
  'voiceless cousin',
  'dulce llorona',
  'confiscation',
  'mentorship',
  'covert kisses',
  'endless lingering',
  'unsatisfied greed',
  'sequined escapade',
];
export const darknessTwo = [
  'darkness',
  'fire',
  'ideal',
  'chatterbox',
  'universe',
  'Swiss Alps',
  'bullshit',
  'hunger',
  'housecat',
  'unmoored body',
  'growth',
  'vapour',
  'sopa',
  'altar',
  'sparrows',
  'gloaming',
  'wistful',
  'other',
  'night',
];
export const eternalImmanence = [
  'eternal immanence',
  'Catholic guilt',
  'falling rain',
  'outer rings',
  'everlasting black',
  'safety zone',
  'infernal spin machine',
  'famished week at sea',
  'boundary',
  'gravitational orbit',
  'smallest seed',
  'makeshift meaning',
  'mucho mucho amor',
  'hollow bone',
  'indefatigable relations',
  'long life',
  'immediate initiate',
  'suspended self',
  'faster-faster',
];
export const considered = [
  'considered',
  'absorbed',
  'wept',
  'underestimated',
  'assumed',
  'whined',
  'loathed',
  'vilified',
  'hoped',
  'consecrated',
  'longed to escape',
  'birthed',
  'shivered',
  'sentado',
  'x-rayed',
  'recalled',
  'assessed',
  'farted',
  'doubted',
  'accelerated',
];
export const alive = [
  'alive',
  'green',
  'unnecessary',
  'the true king',
  'breathing',
  'penitent',
  'of value',
  'done',
  'figmented',
  'fixed',
  'an animal',
  'yearning',
  'muerto',
  'conscious',
  'speaking',
  'aloof',
  'alight',
  'growing',
  'fluttering',
];
export const lurking = [
  'lurking',
  'breathing',
  'scheming',
  'swimming quickly',
  'hiding',
  'fishing',
  'worthy of our attention',
  'defacing',
  'dissolved',
  'alleging',
  'finite',
  'staring',
  'yawning',
  'engañando',
  'proferring',
  'gesturing',
  'haunting',
  'looking',
  'smiling',
  'explusive',
];
export const light = [
  'light',
  'pond',
  'tall grass',
  'herd of camels',
  'sunlight',
  'bladder',
  'daily attempts to fuck us over',
  'electoresses',
  'past',
  'mind',
  'crescendo',
  'aftermath',
  'desert',
  'sancocho de gallina',
  'confines',
  'music',
  'radiation',
  'lantern',
  'vast void',
  'dawn',
];
export const darkHairedStranger = [
  'dark-haired stranger',
  'potted plants',
  'doubts',
  'will-o-the-wisp',
  'angry plaintiff',
  'angry dog',
  'sycophantic enablers',
  'blende',
  'rosy-fingered dawn',
  'incandescent soil',
  'rattling carriage lanterns',
  'blessed dead',
  'heavy-handed hoarders',
  'búho exigente',
  'free market',
  'Bowler-hatted guest',
  'blonde demon',
  'light-hearted friend',
  'yellow bird',
  'schoolhall assembly',
];
export const greeted = [
  'greeted',
  'watered',
  'swaddled',
  'said hello',
  'watched',
  'coated',
  'tolerated',
  'espied',
  'blanketed',
  'pawed',
  'dismissed',
  'caressed',
  'escupió',
  'cornered',
  'explained',
  'welcomed',
  'granted',
  'helped',
  'erupted',
];
export const mutteredFrenchAndGerman = [
  'muttered French and German',
  'tired',
  'veiled',
  'left-behind',
  'lonely',
  'bread crumb',
  'politically motivated sense',
  'dehydrated eyes and sailor',
  'sodden wool',
  'translucent palms',
  'shivered',
  'muddied astral and earthly',
  'difundir el colonialismo y el capitalismo',
  'carbon index futures',
  'Español y Inglés etiquetero',
  'spun Spanish tongues',
  'buttered French toast and liquid',
  'eccentric',
  'solidarity',
];
export const knittedUsBlankets = [
  'knitted us blankets',
  'gave us boxes',
  'set the table',
  'shared their true selves',
  'planted some trees',
  'flew us a kite overhead',
  'spun us webs',
  'offered us bottles',
  'stitched',
  'gifted us in the crux of the shadows',
  'cooked us crocks',
  'layered on branches',
  'trazó nuestras miserias',
  'forfeited in ignorance',
  'wove us samplers',
  'cut clothes',
  'nipped their blank pages',
  'ont lancé des pierres',
  'raised their fists',
];
export const kidHair = [
  'kid hair',
  'ghost peppers',
  'loneliness',
  'their lives',
  'shade',
  'polystyrene',
  'unfiltered propaganda',
  'salt shakers',
  'tepid water',
  'matted merino',
  'seaweeds and grasses',
  'ground cover',
  'swampy lies',
  'platos rotos',
  'fluctuations',
  "sheep's wool",
  'childrens shoes',
  'woolly sentences',
  'dead insects',
  'I-withstood-it-so-should-you',
];
export const blanketed = [
  'blanketed',
  'washed',
  'soothed',
  'covered',
  'showered',
  'fooled',
  'increased',
  'increased',
  'seeped lanolin',
  'wavered between',
  'comforted',
  'branched off',
  'estirado',
  'shattered',
  'amplified',
  'toasted',
  'blanked',
  'scratched',
  'shuttered',
];
export const blankness = [
  'blankness',
  'dreams',
  'clammering',
  'quietness',
  'darkness',
  'minotaur',
  'feeling of meh',
  'dishonour',
  'nausea',
  'oil',
  'prismatic sequences',
  'empty sky',
  'voices',
  'enfermedad',
  'bedrock',
  'amplitudes',
  'emptiness',
  'blanketness',
  'skins',
  'choices',
];

export const contributors = [
  'Andy Weaver',
  'Dani Spinosa',
  'Jesse Pajuaar',
  'Alex Spinosa',
  'Lisa Spinosa',
  'Sagan Yee',
  'Amanda Earl',
  'Jay Miller',
  'Moira Walsh',
  'Claire Lacey',
  'nina jane drystek',
  'Conyer Clayton',
  'Simon Brown',
  'Jacqueline Valencia',
  'Kyle Flemmer',
  'Kavi Duvori',
  'Geoffrey Nilson',
  'Eric Schmaltz',
  'Andrée-Anne Roussel',
  'Elee Kraljii Gardiner',
];
