import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabaseUrl = process.env.NEXT_PUBLIC_DATABASE_URL;
const key = process.env.NEXT_PUBLIC_SUPABASE_KEY;

const lexicon = [
  { content: 'lights', blank: 'lights' },
  { content: 'paints', blank: 'lights' },
  { content: 'children', blank: 'lights' },
  { content: 'moon', blank: 'lights' },
  { content: 'fire', blank: 'lights' },
  { content: 'eyes', blank: 'lights' },
  { content: 'fuckwads', blank: 'lights' },
  { content: 'snorsauges', blank: 'lights' },
  { content: 'crabs', blank: 'lights' },
  { content: 'clairvoyants', blank: 'lights' },
  { content: 'carriages', blank: 'lights' },
  { content: 'fences', blank: 'lights' },
  { content: 'chant', blank: 'lights' },
  { content: 'luces', blank: 'lights' },
  { content: 'clock', blank: 'lights' },
  { content: 'routers', blank: 'lights' },
  { content: 'screens', blank: 'lights' },
  { content: 'lovers', blank: 'lights' },
  { content: 'spirales', blank: 'lights' },
  { content: 'crash', blank: 'lights' },
  { content: 'island', blank: 'lights' },
  { content: 'went', blank: 'went' },
  { content: 'blinked', blank: 'went' },
  { content: 'snuffed', blank: 'went' },
  { content: 'dimmed', blank: 'went' },
  { content: 'blew', blank: 'went' },
  { content: 'barged', blank: 'went' },
  { content: 'took', blank: 'went' },
  { content: 'sat', blank: 'went' },
  { content: 'scattered', blank: 'went' },
  { content: 'dreamed', blank: 'went' },
  { content: 'remained', blank: 'went' },
  { content: 'floated', blank: 'went' },
  { content: 'se', blank: 'went' },
  { content: 'wound', blank: 'went' },
  { content: 'shut', blank: 'went' },
  { content: 'switched', blank: 'went' },
  { content: 'wept', blank: 'went' },
  { content: 'se sont', blank: 'went' },
  { content: 'ascended', blank: 'went' },
  { content: 'out', blank: 'wordOut' },
  { content: 'dark', blank: 'wordOut' },
  { content: 'quiet', blank: 'wordOut' },
  { content: 'off', blank: 'wordOut' },
  { content: 'away', blank: 'wordOut' },
  { content: 'in', blank: 'wordOut' },
  { content: 'over', blank: 'wordOut' },
  { content: 'down', blank: 'wordOut' },
  { content: 'birdseed', blank: 'wordOut' },
  { content: 'below', blank: 'wordOut' },
  { content: 'uncut', blank: 'wordOut' },
  { content: 'feuron', blank: 'wordOut' },
  { content: 'down', blank: 'wordOut' },
  { content: 'on', blank: 'wordOut' },
  { content: 'onward', blank: 'wordOut' },
  { content: 'accélérées', blank: 'wordOut' },
  { content: 'the sky', blank: 'wordOut' },
  { content: 'before', blank: 'before' },
  { content: 'while', blank: 'before' },
  { content: 'underneath', blank: 'before' },
  { content: 'after', blank: 'before' },
  { content: 'eventually', blank: 'before' },
  { content: 'until', blank: 'before' },
  { content: 'despite', blank: 'before' },
  { content: 'thus', blank: 'before' },
  { content: 'in between', blank: 'before' },
  { content: 'yet', blank: 'before' },
  { content: 'tal vez', blank: 'before' },
  { content: 'under', blank: 'before' },
  { content: 'benumbed', blank: 'before' },
  { content: 'au même moment que', blank: 'before' },
  { content: 'expanded', blank: 'before' },
  { content: 'darkness', blank: 'darkness' },
  { content: 'weight', blank: 'darkness' },
  { content: 'songs', blank: 'darkness' },
  { content: 'happiness', blank: 'darkness' },
  { content: 'night', blank: 'darkness' },
  { content: 'Appalachian Mountains', blank: 'darkness' },
  { content: 'apocalypse', blank: 'darkness' },
  { content: 'nines', blank: 'darkness' },
  { content: 'claws', blank: 'darkness' },
  { content: 'snow', blank: 'darkness' },
  { content: 'headlights', blank: 'darkness' },
  { content: 'pipes', blank: 'darkness' },
  { content: 'vapour', blank: 'darkness' },
  { content: 'oscuridad', blank: 'darkness' },
  { content: 'topsoil', blank: 'darkness' },
  { content: 'solitude', blank: 'darkness' },
  { content: 'splendor', blank: 'darkness' },
  { content: 'radiance', blank: 'darkness' },
  { content: 'time', blank: 'darkness' },
  { content: 'accident', blank: 'darkness' },
  { content: 'its inner light', blank: 'darkness' },
  { content: 'turned on', blank: 'turnedOn' },
  { content: 'changed', blank: 'turnedOn' },
  { content: 'hushed', blank: 'turnedOn' },
  { content: 'went away from', blank: 'turnedOn' },
  { content: 'switched on', blank: 'turnedOn' },
  { content: 'followed', blank: 'turnedOn' },
  { content: 'bored', blank: 'turnedOn' },
  { content: 'clattered quietly toward', blank: 'turnedOn' },
  { content: 'sidled from', blank: 'turnedOn' },
  { content: 'swept over', blank: 'turnedOn' },
  { content: 'ran through', blank: 'turnedOn' },
  { content: 'forbade', blank: 'turnedOn' },
  { content: 'contaminated', blank: 'turnedOn' },
  { content: 'distorted', blank: 'turnedOn' },
  { content: 'trickled out of', blank: 'turnedOn' },
  { content: 'left', blank: 'turnedOn' },
  { content: 'slowed', blank: 'turnedOn' },
  { content: 'excited', blank: 'turnedOn' },
  { content: 'stood on', blank: 'turnedOn' },
  { content: 'unchecked love', blank: 'uncheckedLove' },
  { content: 'collections', blank: 'uncheckedLove' },
  { content: 'remembrance', blank: 'uncheckedLove' },
  { content: 'inexcusable thoughts', blank: 'uncheckedLove' },
  { content: 'commitment issues', blank: 'uncheckedLove' },
  { content: 'misplaced faith', blank: 'uncheckedLove' },
  { content: 'ambivalence', blank: 'uncheckedLove' },
  { content: '(water)line', blank: 'uncheckedLove' },
  { content: 'queasy unease', blank: 'uncheckedLove' },
  { content: 'accretion', blank: 'uncheckedLove' },
  { content: 'bellies full', blank: 'uncheckedLove' },
  { content: 'infernal snippings', blank: 'uncheckedLove' },
  { content: 'voiceless cousin', blank: 'uncheckedLove' },
  { content: 'onstruyendo hambre', blank: 'uncheckedLove' },
  { content: 'derision', blank: 'uncheckedLove' },
  { content: 'mentorship', blank: 'uncheckedLove' },
  { content: 'rampant romance', blank: 'uncheckedLove' },
  { content: 'endless listlessness', blank: 'uncheckedLove' },
  { content: 'passion assumée', blank: 'uncheckedLove' },
  { content: 'wildchilding voyage', blank: 'uncheckedLove' },
  { content: 'dialectical way', blank: 'uncheckedLove' },
  { content: 'dandelions', blank: 'dandelions' },
  { content: 'pillows', blank: 'dandelions' },
  { content: 'the small things', blank: 'dandelions' },
  { content: 'wood', blank: 'dandelions' },
  { content: 'ashes', blank: 'dandelions' },
  { content: 'out-of-print paperbacks', blank: 'dandelions' },
  { content: 'assholes', blank: 'dandelions' },
  { content: 'stomach', blank: 'dandelions' },
  { content: 'chickadees', blank: 'dandelions' },
  { content: 'minnows', blank: 'dandelions' },
  { content: 'ivy', blank: 'dandelions' },
  { content: 'chance', blank: 'dandelions' },
  { content: 'arroz con pollo', blank: 'dandelions' },
  { content: 'industry', blank: 'dandelions' },
  { content: 'sparrows', blank: 'dandelions' },
  { content: 'blueberry bushes', blank: 'dandelions' },
  { content: 'every hour', blank: 'dandelions' },
  { content: 'caresses', blank: 'dandelions' },
  { content: 'discovery', blank: 'dandelions' },
  { content: 'being', blank: 'dandelions' },
  { content: 'unchecked love', blank: 'uncheckedLoveTwo' },
  { content: 'union dues', blank: 'uncheckedLoveTwo' },
  { content: 'dreams', blank: 'uncheckedLoveTwo' },
  { content: 'depths', blank: 'uncheckedLoveTwo' },
  { content: 'fear', blank: 'uncheckedLoveTwo' },
  { content: 'mild confusion', blank: 'uncheckedLoveTwo' },
  { content: 'laughing our fucking asses off', blank: 'uncheckedLoveTwo' },
  { content: 'queasy unease', blank: 'uncheckedLoveTwo' },
  { content: 'ecology', blank: 'uncheckedLoveTwo' },
  { content: 'floating desires', blank: 'uncheckedLoveTwo' },
  { content: 'hard-pressed terror', blank: 'uncheckedLoveTwo' },
  { content: 'voiceless cousin', blank: 'uncheckedLoveTwo' },
  { content: 'dulce llorona', blank: 'uncheckedLoveTwo' },
  { content: 'confiscation', blank: 'uncheckedLoveTwo' },
  { content: 'mentorship', blank: 'uncheckedLoveTwo' },
  { content: 'covert kisses', blank: 'uncheckedLoveTwo' },
  { content: 'endless lingering', blank: 'uncheckedLoveTwo' },
  { content: 'unsatisfied greed', blank: 'uncheckedLoveTwo' },
  { content: 'sequined escapade', blank: 'uncheckedLoveTwo' },
  { content: 'fear', blank: 'uncheckedLoveTwo' },
  { content: 'darkness', blank: 'darknessTwo' },
  { content: 'fire', blank: 'darknessTwo' },
  { content: 'ideal', blank: 'darknessTwo' },
  { content: 'chatterbox', blank: 'darknessTwo' },
  { content: 'universe', blank: 'darknessTwo' },
  { content: 'Swiss Alps', blank: 'darknessTwo' },
  { content: 'bullshit', blank: 'darknessTwo' },
  { content: 'hunger', blank: 'darknessTwo' },
  { content: 'housecat', blank: 'darknessTwo' },
  { content: 'unmoored body', blank: 'darknessTwo' },
  { content: 'growth', blank: 'darknessTwo' },
  { content: 'vapour', blank: 'darknessTwo' },
  { content: 'sopa', blank: 'darknessTwo' },
  { content: 'altar', blank: 'darknessTwo' },
  { content: 'sparrows', blank: 'darknessTwo' },
  { content: 'gloaming', blank: 'darknessTwo' },
  { content: 'wistful', blank: 'darknessTwo' },
  { content: 'other', blank: 'darknessTwo' },
  { content: 'night', blank: 'darknessTwo' },
  { content: 'spores', blank: 'darknessTwo' },
  { content: 'eternal immanence', blank: 'eternalImmanence' },
  { content: 'Catholic guilt', blank: 'eternalImmanence' },
  { content: 'falling rain', blank: 'eternalImmanence' },
  { content: 'outer rings', blank: 'eternalImmanence' },
  { content: 'everlasting black', blank: 'eternalImmanence' },
  { content: 'safety zone', blank: 'eternalImmanence' },
  { content: 'infernal spin machine', blank: 'eternalImmanence' },
  { content: 'famished week at sea', blank: 'eternalImmanence' },
  { content: 'boundary', blank: 'eternalImmanence' },
  { content: 'gravitational orbit', blank: 'eternalImmanence' },
  { content: 'smallest seed', blank: 'eternalImmanence' },
  { content: 'makeshift meaning', blank: 'eternalImmanence' },
  { content: 'mucho mucho amor', blank: 'eternalImmanence' },
  { content: 'hollow bone', blank: 'eternalImmanence' },
  { content: 'indefatigable relations', blank: 'eternalImmanence' },
  { content: 'long life', blank: 'eternalImmanence' },
  { content: 'immediate initiate', blank: 'eternalImmanence' },
  { content: 'suspended self', blank: 'eternalImmanence' },
  { content: 'faster-faster', blank: 'eternalImmanence' },
  { content: 'nexus of Saturnalia', blank: 'eternalImmanence' },
  { content: 'considered', blank: 'considered' },
  { content: 'absorbed', blank: 'considered' },
  { content: 'wept', blank: 'considered' },
  { content: 'underestimated', blank: 'considered' },
  { content: 'assumed', blank: 'considered' },
  { content: 'whined', blank: 'considered' },
  { content: 'loathed', blank: 'considered' },
  { content: 'vilified', blank: 'considered' },
  { content: 'hoped', blank: 'considered' },
  { content: 'consecrated', blank: 'considered' },
  { content: 'longed to escape', blank: 'considered' },
  { content: 'birthed', blank: 'considered' },
  { content: 'shivered', blank: 'considered' },
  { content: 'sentado', blank: 'considered' },
  { content: 'x-rayed', blank: 'considered' },
  { content: 'recalled', blank: 'considered' },
  { content: 'assessed', blank: 'considered' },
  { content: 'farted', blank: 'considered' },
  { content: 'doubted', blank: 'considered' },
  { content: 'accelerated', blank: 'considered' },
  { content: 'traced their progress', blank: 'considered' },
  { content: 'alive', blank: 'alive' },
  { content: 'green', blank: 'alive' },
  { content: 'unnecessary', blank: 'alive' },
  { content: 'the true king', blank: 'alive' },
  { content: 'breathing', blank: 'alive' },
  { content: 'penitent', blank: 'alive' },
  { content: 'of value', blank: 'alive' },
  { content: 'done', blank: 'alive' },
  { content: 'figmented', blank: 'alive' },
  { content: 'fixed', blank: 'alive' },
  { content: 'an animal', blank: 'alive' },
  { content: 'yearning', blank: 'alive' },
  { content: 'muerto', blank: 'alive' },
  { content: 'conscious', blank: 'alive' },
  { content: 'speaking', blank: 'alive' },
  { content: 'aloof', blank: 'alive' },
  { content: 'alight', blank: 'alive' },
  { content: 'growing', blank: 'alive' },
  { content: 'fluttering', blank: 'alive' },
  { content: 'chipping', blank: 'alive' },
  { content: 'lurking', blank: 'lurking' },
  { content: 'breathing', blank: 'lurking' },
  { content: 'scheming', blank: 'lurking' },
  { content: 'swimming quickly', blank: 'lurking' },
  { content: 'hiding', blank: 'lurking' },
  { content: 'fishing', blank: 'lurking' },
  { content: 'worthy of our attention', blank: 'lurking' },
  { content: 'defacing', blank: 'lurking' },
  { content: 'dissolved', blank: 'lurking' },
  { content: 'alleging', blank: 'lurking' },
  { content: 'finite', blank: 'lurking' },
  { content: 'staring', blank: 'lurking' },
  { content: 'yawning', blank: 'lurking' },
  { content: 'engañando', blank: 'lurking' },
  { content: 'proferring', blank: 'lurking' },
  { content: 'gesturing', blank: 'lurking' },
  { content: 'haunting', blank: 'lurking' },
  { content: 'looking', blank: 'lurking' },
  { content: 'smiling', blank: 'lurking' },
  { content: 'explusive', blank: 'lurking' },
  { content: 'breaking the rot', blank: 'lurking' },
  { content: 'light', blank: 'light' },
  { content: 'pond', blank: 'light' },
  { content: 'tall grass', blank: 'light' },
  { content: 'herd of camels', blank: 'light' },
  { content: 'sunlight', blank: 'light' },
  { content: 'bladder', blank: 'light' },
  { content: 'daily attempts to fuck us over', blank: 'light' },
  { content: 'electoresses', blank: 'light' },
  { content: 'past', blank: 'light' },
  { content: 'mind', blank: 'light' },
  { content: 'crescendo', blank: 'light' },
  { content: 'aftermath', blank: 'light' },
  { content: 'desert', blank: 'light' },
  { content: 'sancocho de gallina', blank: 'light' },
  { content: 'confines', blank: 'light' },
  { content: 'music', blank: 'light' },
  { content: 'radiation', blank: 'light' },
  { content: 'lantern', blank: 'light' },
  { content: 'vast void', blank: 'light' },
  { content: 'dawn', blank: 'light' },
  { content: 'pith', blank: 'light' },
  { content: 'dark-haired stranger', blank: 'darkHairedStranger' },
  { content: 'potted plants', blank: 'darkHairedStranger' },
  { content: 'doubts', blank: 'darkHairedStranger' },
  { content: 'will-o-the-wisp', blank: 'darkHairedStranger' },
  { content: 'angry plaintiff', blank: 'darkHairedStranger' },
  { content: 'angry dog', blank: 'darkHairedStranger' },
  { content: 'sycophantic enablers', blank: 'darkHairedStranger' },
  { content: 'blende', blank: 'darkHairedStranger' },
  { content: 'rosy-fingered dawn', blank: 'darkHairedStranger' },
  { content: 'incandescent soil', blank: 'darkHairedStranger' },
  { content: 'rattling carriage lanterns', blank: 'darkHairedStranger' },
  { content: 'blessed dead', blank: 'darkHairedStranger' },
  { content: 'heavy-handed hoarders', blank: 'darkHairedStranger' },
  { content: 'búho exigente', blank: 'darkHairedStranger' },
  { content: 'free market', blank: 'darkHairedStranger' },
  { content: 'Bowler-hatted guest', blank: 'darkHairedStranger' },
  { content: 'blonde demon', blank: 'darkHairedStranger' },
  { content: 'light-hearted friend', blank: 'darkHairedStranger' },
  { content: 'yellow bird', blank: 'darkHairedStranger' },
  { content: 'schoolhall assembly', blank: 'darkHairedStranger' },
  { content: 'spirits', blank: 'darkHairedStranger' },
  { content: 'greeted', blank: 'greeted' },
  { content: 'watered', blank: 'greeted' },
  { content: 'swaddled', blank: 'greeted' },
  { content: 'said hello', blank: 'greeted' },
  { content: 'watched', blank: 'greeted' },
  { content: 'coated', blank: 'greeted' },
  { content: 'tolerated', blank: 'greeted' },
  { content: 'espied', blank: 'greeted' },
  { content: 'blanketed', blank: 'greeted' },
  { content: 'pawed', blank: 'greeted' },
  { content: 'dismissed', blank: 'greeted' },
  { content: 'caressed', blank: 'greeted' },
  { content: 'escupió', blank: 'greeted' },
  { content: 'cornered', blank: 'greeted' },
  { content: 'explained', blank: 'greeted' },
  { content: 'welcomed', blank: 'greeted' },
  { content: 'granted', blank: 'greeted' },
  { content: 'helped', blank: 'greeted' },
  { content: 'erupted', blank: 'greeted' },
  { content: 'waltzed', blank: 'greeted' },
  { content: 'muttered French and German', blank: 'mutteredFrenchAndGerman' },
  { content: 'tired', blank: 'mutteredFrenchAndGerman' },
  { content: 'veiled', blank: 'mutteredFrenchAndGerman' },
  { content: 'left-behind', blank: 'mutteredFrenchAndGerman' },
  { content: 'lonely', blank: 'mutteredFrenchAndGerman' },
  { content: 'bread crumb', blank: 'mutteredFrenchAndGerman' },
  { content: 'politically motivated sense', blank: 'mutteredFrenchAndGerman' },
  { content: 'dehydrated eyes and sailor', blank: 'mutteredFrenchAndGerman' },
  { content: 'sodden wool', blank: 'mutteredFrenchAndGerman' },
  { content: 'translucent palms', blank: 'mutteredFrenchAndGerman' },
  { content: 'shivered', blank: 'mutteredFrenchAndGerman' },
  { content: 'muddied astral and earthly', blank: 'mutteredFrenchAndGerman' },
  { content: 'difundir el colonialismo y el capitalismo', blank: 'mutteredFrenchAndGerman' },
  { content: 'carbon index futures', blank: 'mutteredFrenchAndGerman' },
  { content: 'Español y Inglés etiquetero', blank: 'mutteredFrenchAndGerman' },
  { content: 'spun Spanish tongues', blank: 'mutteredFrenchAndGerman' },
  { content: 'buttered French toast and liquid', blank: 'mutteredFrenchAndGerman' },
  { content: 'eccentric', blank: 'mutteredFrenchAndGerman' },
  { content: 'solidarity', blank: 'mutteredFrenchAndGerman' },
  { content: 'murmured dialects and secrets and', blank: 'mutteredFrenchAndGerman' },
  { content: 'knitted us blankets', blank: 'knittedUsBlankets' },
  { content: 'gave us boxes', blank: 'knittedUsBlankets' },
  { content: 'set the table', blank: 'knittedUsBlankets' },
  { content: 'shared their true selves', blank: 'knittedUsBlankets' },
  { content: 'planted some trees', blank: 'knittedUsBlankets' },
  { content: 'flew us a kite overhead', blank: 'knittedUsBlankets' },
  { content: 'spun us webs', blank: 'knittedUsBlankets' },
  { content: 'offered us bottles', blank: 'knittedUsBlankets' },
  { content: 'stitched', blank: 'knittedUsBlankets' },
  { content: 'gifted us in the crux of the shadows', blank: 'knittedUsBlankets' },
  { content: 'cooked us crocks', blank: 'knittedUsBlankets' },
  { content: 'layered on branches', blank: 'knittedUsBlankets' },
  { content: 'trazó nuestras miserias', blank: 'knittedUsBlankets' },
  { content: 'forfeited in ignorance', blank: 'knittedUsBlankets' },
  { content: 'wove us samplers', blank: 'knittedUsBlankets' },
  { content: 'cut clothes', blank: 'knittedUsBlankets' },
  { content: 'nipped their blank pages', blank: 'knittedUsBlankets' },
  { content: 'ont lancé des pierres', blank: 'knittedUsBlankets' },
  { content: 'raised their fists', blank: 'knittedUsBlankets' },
  { content: 'spun us a myth', blank: 'knittedUsBlankets' },
  { content: 'kid hair', blank: 'kidHair' },
  { content: 'ghost peppers', blank: 'kidHair' },
  { content: 'loneliness', blank: 'kidHair' },
  { content: 'their lives', blank: 'kidHair' },
  { content: 'shade', blank: 'kidHair' },
  { content: 'polystyrene', blank: 'kidHair' },
  { content: 'unfiltered propaganda', blank: 'kidHair' },
  { content: 'salt shakers', blank: 'kidHair' },
  { content: 'tepid water', blank: 'kidHair' },
  { content: 'matted merino', blank: 'kidHair' },
  { content: 'seaweeds and grasses', blank: 'kidHair' },
  { content: 'ground cover', blank: 'kidHair' },
  { content: 'swampy lies', blank: 'kidHair' },
  { content: 'platos rotos', blank: 'kidHair' },
  { content: 'fluctuations', blank: 'kidHair' },
  { content: "sheep's wool", blank: 'kidHair' },
  { content: 'childrens shoes', blank: 'kidHair' },
  { content: 'woolly sentences', blank: 'kidHair' },
  { content: 'dead insects', blank: 'kidHair' },
  { content: 'I-withstood-it-so-should-you', blank: 'kidHair' },
  { content: 'ignorance', blank: 'kidHair' },
  { content: 'blanketed', blank: 'blanketed' },
  { content: 'washed', blank: 'blanketed' },
  { content: 'soothed', blank: 'blanketed' },
  { content: 'covered', blank: 'blanketed' },
  { content: 'showered', blank: 'blanketed' },
  { content: 'fooled', blank: 'blanketed' },
  { content: 'increased', blank: 'blanketed' },
  { content: 'increased', blank: 'blanketed' },
  { content: 'seeped lanolin', blank: 'blanketed' },
  { content: 'wavered between', blank: 'blanketed' },
  { content: 'comforted', blank: 'blanketed' },
  { content: 'branched off', blank: 'blanketed' },
  { content: 'estirado', blank: 'blanketed' },
  { content: 'shattered', blank: 'blanketed' },
  { content: 'amplified', blank: 'blanketed' },
  { content: 'toasted', blank: 'blanketed' },
  { content: 'blanked', blank: 'blanketed' },
  { content: 'scratched', blank: 'blanketed' },
  { content: 'shuttered', blank: 'blanketed' },
  { content: 'coated', blank: 'blanketed' },
  { content: 'blankness', blank: 'blankness' },
  { content: 'dreams', blank: 'blankness' },
  { content: 'clammering', blank: 'blankness' },
  { content: 'quietness', blank: 'blankness' },
  { content: 'darkness', blank: 'blankness' },
  { content: 'minotaur', blank: 'blankness' },
  { content: 'feeling of meh', blank: 'blankness' },
  { content: 'dishonour', blank: 'blankness' },
  { content: 'nausea', blank: 'blankness' },
  { content: 'oil', blank: 'blankness' },
  { content: 'prismatic sequences', blank: 'blankness' },
  { content: 'empty sky', blank: 'blankness' },
  { content: 'voices', blank: 'blankness' },
  { content: 'enfermedad', blank: 'blankness' },
  { content: 'bedrock', blank: 'blankness' },
  { content: 'amplitudes', blank: 'blankness' },
  { content: 'emptiness', blank: 'blankness' },
  { content: 'blanketness', blank: 'blankness' },
  { content: 'skins', blank: 'blankness' },
  { content: 'choices', blank: 'blankness' },
  { content: 'floor', blank: 'blankness' },
];

const contributors = [
  { name: 'Andy Weaver' },
  { name: 'Dani Spinosa' },
  { name: 'Jesse Pajuaar' },
  { name: 'Alex Spinosa' },
  { name: 'Lisa Spinosa' },
  { name: 'Sagan Yee' },
  { name: 'Amanda Earl' },
  { name: 'Jay Miller' },
  { name: 'Moira Walsh' },
  { name: 'Claire Lacey' },
  { name: 'nina jane drystek' },
  { name: 'Conyer Clayton' },
  { name: 'Simon Brown' },
  { name: 'Jacqueline Valencia' },
  { name: 'Kyle Flemmer' },
  { name: 'Kavi Duvori' },
  { name: 'Geoffrey Nilson' },
  { name: 'Eric Schmaltz' },
  { name: 'Andrée-Anne Roussel' },
  { name: 'Elee Kraljii Gardiner' },
  { name: 'Ellen Chang-Richardson' },
];

async function populateWhenLexicon() {
  const supabase = createClient(supabaseUrl, key);
  try {
    const { data, error } = await supabase.from('when_lexicon').insert(lexicon);

    if (error) {
      console.error('Error inserting data:', error.message);
      return;
    }

    console.log('Data inserted successfully:', data);
  } catch (err) {
    console.error('Error:', err);
  }
}

populateWhenLexicon();
