export const lines = [
  "Cripes, Charlie, stop yelling—it wasn't even your idea.",
  "Farming is never more than an extension of event, but I haven't read any blustery manifestos from those open fields.",
  "It isn't incorrect to call skin our container, just as it's reasonable to say that living bodies are engines of joy, as they are the only place in the universe where it occurs.",
  'After schooling in the nineties, I am so fucking glad we\'ve stopped obsessing over academic circle-jerks like "what is postmodernism?"',
  "Very few saplings, I'd imagine, dream of growing up to be several hundred copies of Poetry magazine's August 1913 issue containing Joyce Kilmer's \"Trees.\"",
  "A fart is never more than an extension of contentment, but the dog still seems confused when she clears a room.",
  "Science can explain why liquid fills every part of a cup but that doesn't make the shoreline less magical, how the water caresses the land, how it swells onto and even into the sand, traces it with an incessant, astonished fidelity that the scientist must internalize as the image of love.",
  "The world contains no repetition because Stein argued the world contains no repetition.",
  "The world contains no repetition because Heraclitus argued the world contains no repetition.",
  "But one can step into the same bathwater twice, and that's gross.",
  "I contain multitudes of repetition because I am obviously neither Heraclitus nor Stein, but in that sense I become uniquely redundant.",
  "What are these screaming sons before me every day but ships of Theseus I can neither rebuild nor replace?",
  "\"Uniquely redundant\" is the perfect description of most poetry, including Olson's, but he'd likely hate that idea.",
  "Language wears the world like a shell, the world is the shape language expands to fill, and so we get the words we deserve: mass shooting, cointelpro, apparatchik, tourniquet—but also canticle, lilac, solace.",
  "Inside the hurricane, the eye; inside the spiral, the nautilus.",
  "In everything, Neruda's cornerstone of the structure. What is reading but a folie à deux?",
  "If you are born white, straight, and male but hate the house you've inherited, what tools can you use to dismantle it?",
  "The mind thinks, hands grasp, lungs breathe, the heart, which only seems to be a metronome, the heart is where we go to die, over and over.",
  "And in the end, there is the final form, the one we become without knowing, the one that we no longer allow each other, the pleasure of digging into the earth, the joy of shovelling the earth closed again, over one another, an elemental interlacing so like, I must imagine, the way our parents, and we ourselves, pulled the covers over the stilling body of the exhausted child.",
  "If form is what happens, how can we tell an answer from a chance?",
  "We end as we so often do, staring with pride at the bridge we've suspended between us, one of us drawing attention to the beauty of the overhead beams while quietly grinding his heel into the riverbed to bury the leftover bolt.",
  "As a middle-aged guy born in the '70s, I am completely baffled by both the form and the content, the actuality and the idea of, Timothée Chalamet.",
];

export const fonts = [
  "Arial",
  "Verdana",
  "Helvetica",
  "Tahoma",
  "Trebuchet MS",
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Courier New",
  "Brush Script",
];
